//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCandidate
    {
        public int CandidateID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailID { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> LastTestGivenDate { get; set; }
    }
}
