//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public string EmployeeID { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> LastTestGivenDate { get; set; }
    }
}
