//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonalityQues
    {
        public int PQuesID { get; set; }
        public string PersonalityQuestion { get; set; }
        public Nullable<int> YES { get; set; }
        public Nullable<int> NO { get; set; }
        public Nullable<int> UNCERTAIN { get; set; }
        public int PCategoryID { get; set; }
    }
}
