//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestions
    {
        public int QuestionID { get; set; }
        public int SectionID { get; set; }
        public string QuesDescription { get; set; }
        public string AnsOption1 { get; set; }
        public string AnsOption2 { get; set; }
        public string AnsOption3 { get; set; }
        public string AnsOption4 { get; set; }
        public string CorrectAns { get; set; }
    
        public virtual QuestionCategory QuestionCategory { get; set; }
    }
}
