//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int TestID { get; set; }
        public int QuesCategoryID { get; set; }
        public string Emp_Cand_ID { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
